import os
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv

load_dotenv()

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    client_id=os.getenv('SPOTIPY_CLIENT_ID'),
    client_secret=os.getenv('SPOTIPY_CLIENT_SECRET'),
    redirect_uri=os.getenv('SPOTIPY_REDIRECT_URI'),
    scope="playlist-modify-private playlist-read-private user-library-read",
    open_browser=True
))

if __name__ == "__main__":
    user = sp.current_user()
    user_id = user['id']

    saved_tracks = sp.current_user_saved_tracks(limit=10, offset=0)
    track_uris = [item['track']['uri'] for item in saved_tracks['items']]

    playlist_name = "Top Liked Songs, Autogenerated"
    playlists = sp.current_user_playlists(limit=50)
    playlist_id = None

    for playlist in playlists["items"]:
        print(playlist["name"])
        if playlist["name"] == playlist_name:
            playlist_id = playlist["id"]
            break

    if playlist_id is None:
        new_playlist = sp.user_playlist_create(
            user=user_id,
            name=playlist_name,
            public=False
        )
        playlist_id = new_playlist["id"]

    sp.playlist_replace_items(playlist_id=playlist_id, items=track_uris + track_uris + track_uris)
